#!/bin/sh
#
# @name Navputer attached to a Gazebo x500 flown by another PX4 instance
#
# @type Quadrotor
#
# Sensors-only gz_bridge (no actuator outputs): start the flight-controller
# instance first (e.g. make px4_sitl gz_x500), then run this one with -i 1.
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_STANDALONE=${PX4_GZ_STANDALONE:=1}
PX4_GZ_MODEL_NAME=${PX4_GZ_MODEL_NAME:=x500_0}
PX4_GZ_PASSIVE=${PX4_GZ_PASSIVE:=1}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.2
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.2
param set-default CA_ROTOR3_KM -0.05

param set-default EKF2_SENS_EN 3855 # mask out AGP0-3 and ranging beacon (default 8191, minus bits 4,5,6,7,12)

param set-default EKF2_AGP0_ID 111 # MLAT source
param set-default EKF2_AGP0_CTRL 1
param set-default EKF2_AGP0_NOISE 250

# Navputer HW setup
param set-default NPT_GPS_INSTANCE 1 # clean copy of gz GPS republished by spoofer
param set-default NPT_GPS_CTRL 7
param set-default NPT_SD_AUX_INST 1 # aux_global_position instance #0 (Beacon MLAT)

# Gazebo has no ranging beacon simulation (SIH only)
param set-default NPT_RNGBC_CTRL 0
param set-default NPT_FUSE_RNGBC 0

param set-default NPT_FUSE_BARO 1
param set-default NPT_FUSE_MAG 1
param set-default NPT_FUSE_AGP0 1
param set-default NPT_FUSE_GPS 1
param set-default NPT_FC_AGP_LATCH 5.0
param set-default NPT_FC_SD_EN 1

param set-default CAL_MAG_COMP_TYP 0

spoofer start
navputer start
navput_tunnel start
